In [1]:
import pandas
from keras.models import Sequential
from keras.layers import Dense
from keras.wrappers.scikit_learn import KerasClassifier
from keras.utils import np_utils
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.preprocessing import LabelEncoder
from sklearn.pipeline import Pipeline
import numpy as np

In [30]:
num_hands = 6

In [24]:
# define baseline model
def baseline_model():
    # create model
    model = Sequential()
    model.add(Dense(8, input_dim=42, activation='relu'))
    model.add(Dense(num_hands, activation='softmax'))
    # Compile model
    model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
    return model


In [25]:

# load dataset
dataframe = pandas.read_csv("hands.csv", header=None)
dataset = dataframe.values
X = dataset[:,0:42].astype(float)
Y = dataset[:,42]

# encode class values as integers
encoder = LabelEncoder()
encoder.fit(Y)
encoded_Y = encoder.transform(Y)
# convert integers to dummy variables (i.e. one hot encoded)
dummy_y = np_utils.to_categorical(encoded_Y)



In [31]:
np.max(encoded_Y)

5

In [14]:
dummy_y

array([[1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       ...,
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.]], dtype=float32)

In [26]:
m = baseline_model()
m.fit(X, dummy_y, epochs = 300, batch_size = 20, verbose = 0)


In [27]:
scores = m.evaluate(X, dummy_y, verbose=0)
print("%s: %.2f%%" % (m.metrics_names[1], scores[1]*100))

accuracy: 98.38%


In [28]:
predictions = m.predict(X)
np.argmax(predictions, axis=1)

14/14 [==============================] - 0s 2ms/step


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 0, 0, 0, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,

In [29]:
a = [[0.48642781376838684,0.36702558398246765,0.5260230898857117,0.3339691162109375,0.5580445528030396,0.28820568323135376,0.5794381499290466,0.2459271401166916,0.5669881105422974,0.21265211701393127,0.5247182250022888,0.20192761719226837,0.5437151789665222,0.1514180600643158,0.5538244247436523,0.17402178049087524,0.5566861033439636,0.2041478306055069,0.49967077374458313,0.18848754465579987,0.50615394115448,0.11655840277671814,0.5088326334953308,0.07021389901638031,0.5097015500068665,0.025169089436531067,0.4753575921058655,0.19341573119163513,0.4795897305011749,0.12667110562324524,0.48349064588546753,0.08087553083896637,0.4872761070728302,0.03864283859729767,0.45062029361724854,0.21112781763076782,0.45106902718544006,0.1577337086200714,0.45321497321128845,0.12240836769342422,0.45823049545288086,0.08918619155883789
]]
p = m.predict(a)
print(p)
np.argmax(p, axis=1)

1/1 [==============================] - 0s 130ms/step
[[8.1090024e-05 2.2007678e-01 1.1659393e-02 3.5065598e-06 1.7228553e-02
  7.5095069e-01]]


array([5])